import type { InboundMessage } from "../../types/inbound-messages.js";

/**
 * Slash passthrough trace context — always set as a group or not at all.
 *
 * Generated by SlashCommandService for a single passthrough request;
 * correlates the user_message with a specific slash command invocation.
 *
 * @internal Not part of the wire protocol. Populated only by sendUserMessage()
 *           in SlashCommandService — never arrives from an external consumer.
 */
export type SlashTraceContext = {
  traceId: string;
  slashRequestId: string;
  slashCommand: string;
};

/**
 * Requests that flow into SessionRuntime from transports/programmatic callers.
 *
 * `user_message` is extended with an optional `traceContext` group carrying
 * slash passthrough trace metadata. The group is either fully present or absent —
 * it is not part of the wire protocol and is populated only by sendUserMessage().
 * All other command types are structurally equivalent to InboundMessage.
 */
export type InboundCommand =
  | (Extract<InboundMessage, { type: "user_message" }> & {
      traceContext?: SlashTraceContext;
    })
  | Exclude<InboundMessage, { type: "user_message" }>;

/**
 * Advisory commands emitted by policy services and handled by SessionRuntime.
 */
export type PolicyCommand =
  | { type: "reconnect_timeout" }
  | { type: "idle_reap" }
  | { type: "capabilities_timeout" };
